# Generated by Django 4.1.1 on 2023-05-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
